name: Docker Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-dse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Management API in docker
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>artifactory-snapshots</id>
                <username>${{ secrets.ARTIFACTORY_USERNAME }}</username>
                <password>${{ secrets.ARTIFACTORY_PASSWORD }}</password>
              </server>
              <server>
                <id>artifactory-releases</id>
                <username>${{ secrets.ARTIFACTORY_USERNAME }}</username>
                <password>${{ secrets.ARTIFACTORY_PASSWORD }}</password>
             </server>
           </servers>
          </settings>
          EOF
          cp ~/.m2/settings.xml settings.xml
      - name: Get Release Version
        id: get_version
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      - name: Publish DSE 6.8 to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: emerkle826/dse-mgmtapi-6_8
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: '${{ env.RELEASE_VERSION }}'
          dockerfile: Dockerfile-dse-68
      - name: Publish 4.0 to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: emerkle826/cass-mgmtapi
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: '4.0.0,4.0.0-${{ env.RELEASE_VERSION }}'
          dockerfile: Dockerfile-4_0
  build-oss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Publish 3.11.7 to Registry
        run: |
          RELEASE_VERSION="${GITHUB_REF##*/}"
          docker buildx build --push \
            --build-arg CASSANDRA_VERSION=3.11.7 \
            --tag emerkle826/cass-mgmtapi:3.11.7 \
            --tag emerkle826/cass-mgmtapi3.11.7-:$RELEASE_VERSION \
            --file Dockerfile-oss \
            --target oss311 \
            --platform linux/amd64,linux/arm64 .
      - name: Publish 3.11.8 to Registry
        run: |
          RELEASE_VERSION="${GITHUB_REF##*/}"
          docker buildx build --push \
            --build-arg CASSANDRA_VERSION=3.11.8 \
            --tag emerkle826/cass-mgmtapi:3.11.8 \
            --tag emerkle826/cass-mgmtapi3.11.8-:$RELEASE_VERSION \
            --file Dockerfile-oss \
            --target oss311 \
            --platform linux/amd64,linux/arm64 .
      - name: Publish 3.11.9 to Registry
        run: |
          RELEASE_VERSION="${GITHUB_REF##*/}"
          docker buildx build --push \
            --build-arg CASSANDRA_VERSION=3.11.9 \
            --tag emerkle826/cass-mgmtapi:3.11.9 \
            --tag emerkle826/cass-mgmtapi3.11.9-:$RELEASE_VERSION \
            --file Dockerfile-oss \
            --target oss311 \
            --platform linux/amd64,linux/arm64 .
      - name: Publish 3.11.10 to Registry
        run: |
          RELEASE_VERSION="${GITHUB_REF##*/}"
          docker buildx build --push \
            --build-arg CASSANDRA_VERSION=3.11.10 \
            --tag emerkle826/cass-mgmtapi:3.11.10 \
            --tag emerkle826/cass-mgmtapi3.11.10-:$RELEASE_VERSION \
            --file Dockerfile-oss \
            --target oss311 \
            --platform linux/amd64 .
